# Configuration file for IPO data sites
# Add site names and URLs below

sites:
  - name: "NSE India (National Stock Exchange)"
    url: "https://www.nseindia.com/"
  - name: "BSE India"
    url: "https://www.bseindia.com/?"
  - name: "Chittorgarh IPO"
    url: "https://www.chittorgarh.com/"
  - name: "IPO Watch"
    url: "https://ipowatch.in/ipo-grey-market-premium-latest-ipo-gmp/"
  - name: "Investorgain"
    url: "https://www.investorgain.com/report/live-ipo-gmp/331/"
